### ISSUE TITLE
Не дороблено TODO (відсутня схема обʼєкту)

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#20]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/administrative/regulation-management/admin-portal/data-model/admin-portal-data-model-xml-changelog-serialization.adoc?plain=1#L192-L195

**Comment by antontuhai** [comment]
The note is no longer relevant. The article is completed.
