### ISSUE TITLE
Неробоче посилання

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#21]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/administrative/regulation-management/admin-portal/business-processes/bpmn-modeler.adoc?plain=1#L34

**Comment by antontuhai** [comment]
Fixed link for ua and en versions:

https://epam.github.io/edp-ddm-architecture/ua/platform/1.9.6/arch/architecture/registry/administrative/regulation-management/admin-portal/business-processes/bpmn-modeler.html

https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/arch/architecture/registry/administrative/regulation-management/admin-portal/business-processes/bpmn-modeler.html
