### ISSUE TITLE
Англійські терміни написані кирилицею замість перекладу

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#22]
"тултипу"
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/administrative/regulation-management/bp-script-groovy-editor.adoc?plain=1#L33

"Місконфігурація"
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/administrative/regulation-management/bp-script-groovy-editor.adoc?plain=1#L274

"заонборджений" та "імедж"
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/administrative/regulation-management/bp-script-groovy-editor.adoc?plain=1#L282-L284

**Comment by antontuhai** [comment]
Reviewed and fixed all such points.
