### ISSUE TITLE
Не реалізована примітка

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#27]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/operational/audit/overview.adoc?plain=1#L112-L115

**Comment by antontuhai** [comment]
The note is no longer relevant. The article is completed.

**Comment by scorpio-84** [comment]
В такому разі треба цю примітку зі статті забрати
