### ISSUE TITLE
Не зрозуміло сформульовано речення, перефразувати

### ISSUE THREAD

**Issue by VFeorenko** [epam/edp-ddm-architecture#3]
https://epam.github.io/edp-ddm-architecture/ua/platform/1.9.6/index.html

https://prnt.sc/AZtldloKVklV

Такий підхід гарантує збереження визначеного власника даних, і, своєю чергою, збереження відповідальності за дані.

**Comment by antontuhai** [comment]
Fixed and aligned with the english version:

Цей підхід гарантує збереження ідентифікації власника даних, встановлюючи _чітку відповідальність за дані_. Водночас він закладає основу для подальшого розвитку Платформи, визначаючи реєстри як комплекс апаратних та програмних засобів. Ці інструменти розроблені для впровадження вимог, висунутих Міністерством цифрової трансформації України.

This approach guarantees the preservation of data owner identification, establishing _clear data responsibility_. Simultaneously, it lays the groundwork for further Platform enhancements, positioning registries as a complex of hardware and software tools. These tools are designed to implement the requirements the Ministry of Digital Transformation of Ukraine set forth.
