### ISSUE TITLE
Пояснення на схемі в українській версії виконані англійською

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#33]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/ua/modules/arch/pages/architecture/registry/operational/bpms/bpm-save-interim-form-submission.adoc?plain=1#L26

**Comment by antontuhai** [comment]
@VFeorenko Please review

**Comment by VFeorenko** [comment]
На цій сторінці тільки одна схема анлійською - вона може залишатись англійською, тому що посилання в тексті йдуть саме на англійські терміни

**Comment by antontuhai** [comment]
Thank you for the clarification. We're closing this issue.
