### ISSUE TITLE
Відсутній опис технології

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#36]
В інших розділах документації є розїяснення найпростіших термінів, таких як DNS, але на цій сторінці немає розʼяснення що таке OKD та посилання на офіційний сайт та документацію.

https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/installation/okd-requirements.adoc?plain=1#L1-L16

**Comment by antontuhai** [comment]
Extended description for both en and ua versions:
https://github.com/epam/edp-ddm-architecture/commit/fbbfd99acbb47a29e30d8c20ff86d35e57d6c639
