### ISSUE TITLE
Посилання на внутрнішній закритий телеграм-канал Epam

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#38]
https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/registry-management/custom-dns/cp-custom-dns-keycloak.adoc?plain=1#L156

**Comment by antontuhai** [comment]
Fixed: https://github.com/epam/edp-ddm-architecture/commit/f54c54134f58642bfcbf0a07895c8b4f4cf487e0
