### ISSUE TITLE
Відсутнє посилання на репозитарій з Terraform-кодом

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#39]
https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/installation/platform-deployment/platform-aws-deployment.adoc?plain=1#L234-L245

**Comment by antontuhai** [comment]
All the required code with explanations is provided further down in the article.
