### ISSUE TITLE
Відсутня документація по розгортуванню платформи на GCP

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#41]
Замість документації по розгортуванню на GCP наявне посилання на документацію по розгортуванню на AWS.

https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/installation/platform-deployment/platform-gcp-deployment.adoc?plain=1#L11-L12

**Comment by antontuhai** [comment]
Similar to https://github.com/epam/edp-ddm-architecture/issues/40.

The Platform for state registries is cloud-agnostic, allowing for deployment across any cloud environment or even on-premises.

At present, we've tested and verified deployments on AWS and vSphere. Should there be a demand for GCP installation, we'll provide comprehensive instructions.

For now, you can refer to the official OKD documentation for guidance: [Installing OKD on GCP](https://docs.okd.io/4.11/installing/installing_azure/preparing-to-install-on-gcp.html). For comparison, we also offer instructions for AWS deployment: [Deploying the Platform in a public AWS cloud environment](https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/admin/installation/platform-deployment/platform-aws-deployment.html).

All these points have been discussed and confirmed in our stakeholder meetings.
