### ISSUE TITLE
Баг із відображенням Footnote.

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#42]
https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/installation/platform-deployment/platform-vsphere-deployment.adoc?plain=1#L362

https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/installation/platform-deployment/platform-vsphere-deployment.adoc?plain=1#L430

![image](https://github.com/epam/edp-ddm-architecture/assets/144326975/09b244be-6c02-4e72-932d-4700a45cdade)

**Comment by antontuhai** [comment]
Fixed: https://github.com/epam/edp-ddm-architecture/commit/cca09714aef3d5f2e21eac11e41fce4c72a17696
