### ISSUE TITLE
Відсутнє посилання на репозитарій з інсталлером.

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#43]
https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/installation/platform-deployment/platform-vsphere-deployment.adoc?plain=1#L8-L12

**Comment by antontuhai** [comment]
Updated in 7b80c20e2a2d12efe2d4e340110d97de7fb12cd6.
