### ISSUE TITLE
Скріншоти російською

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#44]
На скріншотах інтерфейс Jenkins російською. Не впевнений, що це корректно в наявній ситуації.

https://github.com/epam/edp-ddm-architecture/blob/5127201c9fee2db3cbec7e30936b9b8bf06d1957/docs/ua/modules/admin/pages/backup-restore/control-plane-backup-restore.adoc?plain=1#L27-L28

**Comment by antontuhai** [comment]
Fixed: https://github.com/epam/edp-ddm-architecture/commit/c3231a1a768d2cdce7441cbed701adf93e377c4f
