### ISSUE TITLE
Описано налаштування лише для Windows 

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#45]
Бажано додати опис розгортання для Linux та Mac OS
 
https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/registry-admin/regulations-deploy/registry-admin-deploy-regulation.adoc?plain=1#L1-L10

**Comment by antontuhai** [comment]
The guide primarily focuses on working with the Gerrit repository and the Git Bash console. Git Bash is a cross-platform tool, ensuring consistent interaction with git repositories across various operating systems. This means configurations for different OSs are fundamentally similar, presenting no obstacles for technical professionals.
