### ISSUE TITLE
Посилання не робоче

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#47]
https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/en/modules/registry-develop/pages/registry-admin/regulations-deploy/registry-admin-deploy-regulation.adoc?plain=1#L177

**Comment by antontuhai** [comment]
Fixed in 821da3faafbab0998da57c6d9ce2843016d9bc77.
