### ISSUE TITLE
Не робоче посилання

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#48]
https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/registry-admin/user-notifications/diia/diia-bp-notification.adoc?plain=1#L200-L205

**Comment by antontuhai** [comment]
Fixed in 5a6564d56c7f8b7c16741d5df5c9b8e92b5fa8ab.
