### ISSUE TITLE
Відсутня анлійська версія для сторінок

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#49]
https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/registry-admin/user-notifications/diia/diia-overview.adoc?plain=1#L20-L25

https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/registry-admin/user-notifications/diia/diia-channel-confirmation-temp.adoc?plain=1#L20-L24

https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/registry-admin/user-notifications/diia/diia-bp-notification.adoc?plain=1#L20-L25

**Comment by antontuhai** [comment]
This functionality is specific to the Ukrainian implementation and may not apply or function as described in other contexts or regions.

Translation for these pages is not anticipated.
