### ISSUE TITLE
Виправити лінки. Зараз вони ведуть на внутрішній кластер ЕПАМ

### ISSUE THREAD

**Issue by VFeorenko** [epam/edp-ddm-architecture#5]
https://github.com/epam/edp-ddm-architecture/blob/e400f2a9f8e39109257ab26749ee3832ced5b69d/docs/ua/modules/arch/pages/architecture/registry/operational/ext-systems-simulation/overview.adoc?plain=1#L37-L62

**Comment by antontuhai** [comment]
Fixed in https://github.com/epam/edp-ddm-architecture/issues/35.

> **_NOTE_**: Some repositories are deprecated or intended for use exclusively in the development/deployment of the Platform within Ukraine. They are optional and include implementing specific features and regional requirements for information systems. These comprise:
> * https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/mock/trembita-edr-registry-mock
> * https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/mock/trembita-dracs-registry-mock 
> * https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/mock/trembita-idp-mock-server
