### ISSUE TITLE
Не робоче посилання

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#50]
https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/registry-admin/external-integration/api-publish/rest-soap-api-expose.adoc?plain=1#L119-L124

**Comment by antontuhai** [comment]
Fixed in 4269e1bb326b6a49d5a88e39cf8df21d2672eeda.
