### ISSUE TITLE
Не корректне відображення footnote

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#53]
https://github.com/epam/edp-ddm-architecture/blob/56cf596eb8aae82880c263b63792a20c7303d93c/docs/ua/modules/registry-develop/pages/data-modeling/initial-load/data-initial-data-load-prep.adoc?plain=1#L90

**Comment by antontuhai** [comment]
Fixed in 0ca6bafde8e5ab519d9c0374d498be1b30b3c53a.
