### ISSUE TITLE
В англійській версії відсутні посилання з примітки

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#58]
https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/en/modules/registry-develop/pages/registry-admin/cp-auth-setup/cp-officer-self-registration.adoc?plain=1#L73-L75

**Comment by antontuhai** [comment]
Fixed in 309526686a9e2b6c29ad2ec465614190ecc705a6. 
> **_NOTE_**: The _bp-officer-self-register-auto.adoc_ page is a test scenario applicable only within the Ukrainian market.
