### ISSUE TITLE
В англійській мові посилання українською мовою

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#59]
https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/en/modules/registry-develop/pages/registry-admin/external-integration/ext-integration-overview.adoc?plain=1#L161

https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/en/modules/registry-develop/pages/registry-admin/external-integration/ext-integration-overview.adoc?plain=1#L168

**Comment by antontuhai** [comment]
Fixed in 166687a1d2c88d64ed07f9defc19b9d0131e214f.
