### ISSUE TITLE
Не інформативний приклад

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#60]
https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/ua/modules/registry-develop/pages/registry-admin/external-integration/rest-api-no-trembita.adoc?plain=1#L126-L127

**Comment by antontuhai** [comment]
Fixed in 3a6d128655d07e753be0ed5fac339de00592d789.
