### ISSUE TITLE
Не робочі посилання в англійській версії

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#62]
https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/en/modules/registry-develop/pages/registry-admin/admin-portal/registry-modeling/process-models/components/tab-code.adoc?plain=1#L14

https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/en/modules/registry-develop/pages/registry-admin/admin-portal/registry-modeling/process-models/components/tab-code.adoc?plain=1#L73

**Comment by antontuhai** [comment]
We have reviewed your issue. All existing links are functioning as expected. I'd like to point out that some phrases highlighted with underlining are not intended to be links; it's simply text emphasis.

However, I've made adjustments dabbd05e5f9a47ac687dc85ce23fae75b28e1a5d to these and other documents, adding some xref-links to enhance the documentation's usability and user experience. 

We are closing this issue.
