### ISSUE TITLE
Не інформативний приклад

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#66]
https://github.com/epam/edp-ddm-architecture/blob/f54c54134f58642bfcbf0a07895c8b4f4cf487e0/docs/ua/modules/registry-develop/pages/best-practices/bp-timer-launch.adoc?plain=1#L30-L31

**Comment by antontuhai** [comment]
Fixed in f39ca97bded720f868bfde3399686e7ae9bb6ceb.
