### ISSUE TITLE
Діаграми не співпадають в англійській та українській версіях документу.

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#7]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/en/modules/arch/pages/architecture/platform/administrative/config-management/overview.adoc?plain=1#L31

**Comment by antontuhai** [comment]
Updated and aligned diagram:
https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/arch/architecture/platform/administrative/config-management/overview.html#_technical_design
