### ISSUE TITLE
Українські назви на діаграмі в англійському розділі

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#8]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/en/modules/arch/pages/architecture/platform/administrative/config-management/secure-endpoints/secure-endpoints-tech-design.adoc?plain=1#L13

**Comment by antontuhai** [comment]
Updated diagram and related document:

https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/arch/architecture/platform/administrative/config-management/secure-endpoints.html
