### ISSUE TITLE
В українській версії схеми англійською совою

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#80]
https://github.com/epam/edp-ddm-architecture/blob/c3231a1a768d2cdce7441cbed701adf93e377c4f/docs/ua/modules/testing/pages/performance-testing/performance-testing.adoc?plain=1#L100

https://github.com/epam/edp-ddm-architecture/blob/c3231a1a768d2cdce7441cbed701adf93e377c4f/docs/ua/modules/testing/pages/performance-testing/performance-testing.adoc?plain=1#L105

**Comment by antontuhai** [comment]
Thank you for bringing this to our attention. 

The issue you've highlighted concerns screenshots depicting some of the system's performance capabilities, measured using specialized external tools. These are not part of the Platform. 

We appreciate your understanding and are closing this issue.
