### ISSUE TITLE
Відсутнє зображення

### ISSUE THREAD

**Issue by scorpio-84** [epam/edp-ddm-architecture#9]
https://github.com/epam/edp-ddm-architecture/blob/c94722ef9a473e13a3e954a6ee6d48998f4e6437/docs/en/modules/arch/pages/architecture/platform/operational/secret-management/overview.adoc?plain=1#L24

**Comment by antontuhai** [comment]
Fixed diagram and related document:

- Diagram: https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/arch/_images/architecture/platform/operational/secret-management/secret-management.drawio.svg

- Document: https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/arch/architecture/platform/operational/secret-management/overview.html
